### PR TITLE
change logrus package references to lower case sirupsen

### PR DESCRIPTION
**Pull request by harsh-px**
We need to change all logrus imports to use the lower case Sirupsen to eventually remove hybrid imports (Sirupsen vs sirupsen)

References:
- https://github.com/sirupsen/logrus/issues/451
- https://github.com/sirupsen/logrus/issues/543

Signed-off-by: Harsh Desai <harsh@portworx.com>

### CODE REVIEW

**Comment by pault84** [comment]
won't this break anyone else pulling gossip in that's using Logrus instead of logrus in other parts of their code?

**Comment by harsh-px** [comment]
> won't this break anyone else pulling gossip in that's using Logrus instead of logrus in other parts of their code?

Yes, it will. However, that is no different from us soon going to update other vendor packages that are using lower case sirupsen (for e.g moby). So we will keep this PR approved and parked here. At one go, we will then push all of these case changes.

On a separate node, I'm fixing the CI failure.

**Comment by pault84** [comment]
Yeah, that looked like a vendoring issue.

**Comment by harsh-px** [comment]
Will reopen after fixing the build on the branch.

**Pull request closed without merging**
